namespace: http://www.sylma.org/execution
path : /sylma/action
error :
  page: /error
  # Redirect on action's error to 404
  redirect: true
stats:
  # Display actions infos (memory leak !)
  enable: true
interface : @sylma:import @sylma:self ../path; + /interface.yml;
classes :
  controler :
    name : ActionControler
  action :
    name : XML_Action
  path :
    name : XML_Path
  array :
    name : Action_Array
  processor :
    name : XML_Processor