classes:
  @sylma-classbase : \sylma\modules\timer
  timer :
    file : Collection.php
    name : Collection
  _timer:
    file : Argument.php
    name : Argument
  inspector :
    file : /sylma/modules/inspector/Inspector.php
    name : \Inspector

