classes:
  class:
    name: InspectorClass
    classes :
      comment : InspectorCommentClass
  method:
    name: InspectorMethod
  parameter:
    name: InspectorParameter
  property:
    name: InspectorProperty
  constant:
    name: InspectorConstant
