classes:
  class:
    name: InspectorClass
  method:
    name: InspectorMethod
  parameter:
    name: InspectorParameter
  property:
    name: InspectorProperty
  constant:
    name: InspectorConstant
