classes:
  class:
    name: InspectorClass
    classes :
      comment :
        file : Comment.php
        name : InspectorCommentClass
  method:
    name: InspectorMethod
  parameter:
    name: InspectorParameter
  property:
    name: InspectorProperty
  constant:
    name: InspectorConstant
  element:
    name: XML_Element
