classes:
  controler :
    file : Inspector.php
    name : \Inspector
  class:
    file : Class.php
    name : \InspectorClass
    classes :
      comment :
        file : Comment.php
        name : \InspectorCommentClass
      method:
        file : Method.php
        name: \InspectorMethod
        classes :
          parameter:
            file : Parameter.php
            name : \InspectorParameter
          comment:
            file : Comment.php
            name: \InspectorCommentMethod
      property:
        file : Property.php
        name : \InspectorProperty
        classes :
          comment :
            file : Comment.php
            name : \InspectorCommentProperty
      constant:
        file : Constant.php
        name : \InspectorConstant
  element :
    name : XML_Element
  argument :
    name : \sylma\core\argument\Iterator
