rights:
  owner: root
  group: 0
  mode: 700
  user-mode:
browse :
  excluded : [.svn]
unsafes :
  /sylma/dom2/settings.yml
  #/users/root/dom/simple.eml
  /sylma/core/module/domed.yml
  #/sylma/parser/action/settings.yml
  #/sylma/parser/action/php/settings.yml
classes :
  @sylma-classbase : \sylma\storage\fs
  controler :
    name : Controler
  file :
    name : basic\File
    classes :
      document :
        file : /sylma/dom2/basic/Handler.php
        name : \sylma\dom\basic\Handler
      editable :
        name : basic\editable\File
  directory :
    name : basic\Directory
    classes :
      editable :
        name : basic\editable\Directory
  security :
    name : basic\security\Manager
    classes :
      document :
        file : /sylma/dom2/basic/Handler.php
        name : \sylma\dom\basic\Handler
