classes :
  @sylma-classbase : \sylma\storage\fs
  controler :
    name : Controler
  file :
    interface : file
    name : basic\File
    classes :
      document :
        interface : \sylma\dom\document
        name : \sylma\dom\basic\Document
  directory :
    interface : directory
    name : basic\Directory
  security :
    interface : security\manager
    name : basic\security\Manager
    classes :
      document :
        interface : \sylma\dom\document
        name : \sylma\dom\basic\Document
  