rights:
  owner: root
  group: 0
  mode: 700
  user-mode:
browse :
  excluded : [.svn]
tokens :
  sylma :
    path : sylma
  cache :
    path : .sylma-cache
    propagate : true
  tmp :
    path : .sylma-tmp
    propagate : true
classes :
  @sylma-classbase : \sylma\storage\fs
  controler :
    name : Controler
  file :
    name : basic\File
    classes :
      document :
        file : /sylma/dom2/basic/handler/Rooted.php
        name : \sylma\dom\basic\handler\Rooted
      editable :
        name : basic\editable\File
  directory :
    name : basic\tokened\Directory
    classes :
      editable :
        name : basic\editable\Directory
  security :
    name : basic\security\Manager
    classes :
      document :
        file : /sylma/dom2/basic/handler/Rooted.php
        name : \sylma\dom\basic\handler\Rooted
system :
  rights : 0770