classes :
  @sylma-classbase : \sylma\dom
  document :
    file : basic/Document.php
    name : basic\Document
  element :
    file : basic/Element.php
    name : basic\Element
  collection :
    file : basic/Collection.php
    name : basic\Collection
stats :
  enable : false