classes :
  @sylma-classbase : \sylma\dom
  handler :
    file : basic/handler/Rooted.php
    name : basic\handler\Rooted
  document :
    file : basic/Document.php
    name : basic\Document
  element :
    file : basic/Element.php
    name : basic\Element
  collection :
    file : basic/Collection.php
    name : basic\Collection
  fragment :
    file : basic/Fragment.php
    name : basic\Fragment
  text :
    file : basic/Text.php
    name : basic\Text
stats :
  enable : false
namespaces :
  html : http://www.w3.org/1999/xhtml
  dom : http://www.sylma.org/dom
import-depth : 5