classes :
  controler :
    name : XML_Controler
  document :
    name : XML_Document
  element :
    name : XML_Element
  text :
    name : XML_Text
  attribute :
    name : XML_Attribute
  fragment :
    name : XML_Fragment
  cdata :
    name : XML_CData
  comment :
    name : XML_Comment
  list :
    name : XML_NodeList