classes :
  controler :
    name : XSD_Parser
  element :
    file : Element.php
    name : XSD_Element
  attribute :
    file : Attribute.php
    name : XSD_Attribute
  model :
    file : Model.php
    name : XSD_Model
  group :
    file : Group.php
    name : XSD_Group
  simpletype :
    file : BaseType.php
    name : XSD_BaseType
  complextype :
    file : Type.php
    name : XSD_Type
  particle :
    file : Particle.php
    name : XSD_Particle
